<?php

namespace Zezda\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandleRepository extends EntityRepository
{
	public function countCandleExists($stock, $datetime)
	{
		$qb = $this->createQueryBuilder('b')
			->andWhere('b.stock = :stock')
			->andWhere('b.datetime = :datetime')
			->setParameter('stock', $stock->getTicker())
			->setParameter('datetime', $datetime);

		return $qb->getQuery()->getSingleScalarResult();


	}

	/**
	 * @param $stock - contains stock id
	 *
	 * @return mixed
	 */
	public function findLatestCandleForStock($stock)
	{
		$qb = $this->createQueryBuilder('b')
			->select('b.datetime as datetime')
			->where('b.stock = :stock')
			->addOrderBy('datetime', 'DESC')
			->setParameter('stock', $stock->getId())
			->setMaxResults(1);


		return $qb->getQuery()->getResult();
	}
}
