<?php

namespace Zezda\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
	public function stockExists($ticker, $exchange)
	{
		$qb = $this->createQueryBuilder('b')
			->andWhere('b.ticker = :ticker')
			->andWhere('b.exchange = :exchange')
			->setParameter('ticker', $ticker)
			->setParameter('exchange', $exchange);


		return $qb->getQuery()->getResult();
	}
}
